[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the redirects section as it's not needed for serverless functions
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 